# Generated by Django 3.1.4 on 2021-04-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0003_auto_20210422_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='geolocation',
        ),
    ]
