# Generated by Django 3.1.4 on 2021-04-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0006_auto_20210423_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
